# Site settings
title: KappaG | MyBioinformaticsAdventure
description: "More on my research and PhD projects"
url: "https://kristinagagalova.github.io/MyBioinformaticsAdventure/"
author:
  name: "Kristina Gagalova"
  email: "kgagalova@bcgsc.ca"
  url: ""

# Build settings
baseurl: /MyBioinformaticsAdventure/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
